name: Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-sbt:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
    name: SBT Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: coursier/cache-action@v5
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"
      - name: Build and run tests
        run: sbt jacoco
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/target/scala-2.13/jacoco/report/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 0.0
          min-coverage-changed-files: 80.0
          title: JaCoCo code coverage report - scala:2.13
          update-comment: true
      - name: Get the Coverage info
        run: |
          echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
          echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
      - name: Fail PR if changed files coverage is less than 80%
        if: ${{ steps.jacoco.outputs.coverage-changed-files < 80.0 }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Changed files coverage is less than 80%!')
        
